#! /bin/bash
cd llama.cpp
mkdir build
export GGML_CUDA_ENABLE_UNIFIED_MEMORY=1
export GGML_CUDA_FORCE_MMQ=1
export GGML_CUDA_PEER_MAX_BATCH_SIZE=256
export CUDA_SCALE_LAUNCH_QUEUES=2x

cmake -B build -DGGML_BLAS=ON -DGGML_BLAS_VENDOR=OpenBLAS -DGGML_CUDA=ON -DGGML_NATIVE=OFF -DCMAKE_CUDA_ARCHITECTURES="86;89;90" -DGGML_CUDA_FORCE_MMQ=1 -DGGML_CUDA_PEER_MAX_BATCH_SIZE=256 -DGGML_CUDA_ENABLE_UNIFIED_MEMORY=1 -DBUILD_SHARED_LIBS=OFF 
cmake --build build --config Release -j 6 
