import express from 'express'
import cors from 'cors'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import { promises as fs } from 'node:fs'
import { exec } from 'child_process'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

const app = express()
const PORT = process.env.PORT || 3000
const CONFIGS_DIR = join(__dirname, 'configs')
const SCRIPTS_DIR = join(__dirname, 'scripts')

app.use(cors())
app.use(express.json())
app.use(express.static(join(__dirname, 'dist')))

async function readJsonFile(filename) {
  try {
    const data = await fs.readFile(join(CONFIGS_DIR, filename), 'utf-8')
    return JSON.parse(data)
  } catch (error) {
    return []
  }
}

async function writeJsonFile(filename, data) {
  await fs.writeFile(join(CONFIGS_DIR, filename), JSON.stringify(data, null, 2))
}

async function generateBuildScript(config) {
  let script = '#!/bin/bash\n'
  script += '# Build Script for llama.cpp\n'
  script += `# Generated by Llama Manager\n\n`
  
  script += 'export CUDACXX=/usr/local/cuda/bin/nvcc\n'
  script += 'export GGML_CUDA_ENABLE_UNIFIED_MEMORY=1\n\n'
  
  if (config.envVars) {
    for (const [key, value] of Object.entries(config.envVars)) {
      if (value) {
        script += `export ${key}=${value}\n`
      }
    }
    script += '\n'
  }
  
  script += 'cmake -B build \\\n'
  
  const buildSharedLibs = config.buildSharedLibs !== undefined ? !config.buildSharedLibs : true
  script += `  -DBUILD_SHARED_LIBS=${buildSharedLibs ? 'ON' : 'OFF'} \\\n`
  
  const cmakeTypes = ['Debug', 'Release', 'RelWithDebInfo', 'MinSizeRel']
  const cmakeType = cmakeTypes.includes(config.cmakeBuildType) ? config.cmakeBuildType : 'RelWithDebInfo'
  script += `  -DCMAKE_BUILD_TYPE=${cmakeType} \\\n`
  
  if (config.ggmlCcache) script += '  -DGGML_CCACHE=ON \\\n'
  if (config.ggmlLto) script += '  -DGGML_LTO=ON \\\n'
  if (config.ggmlNative) script += '  -DGGML_NATIVE=ON \\\n'
  
  if (config.ggmlCuda) {
    script += '  -DGGML_CUDA=ON \\\n'
    if (config.ggmlCudaPeerMaxBatchSize) {
      script += `  -DGGML_CUDA_PEER_MAX_BATCH_SIZE=${config.ggmlCudaPeerMaxBatchSize} \\\n`
    }
    if (config.ggmlCudaFa) script += '  -DGGML_CUDA_FA=ON \\\n'
    if (config.ggmlCudaGraphs) script += '  -DGGML_CUDA_GRAPHS=ON \\\n'
    if (config.ggmlCudaForceMmq) script += '  -DGGML_CUDA_FORCE_MMQ=ON \\\n'
    if (config.ggmlCudaForceCublas) script += '  -DGGML_CUDA_FORCE_CUBLAS=ON \\\n'
  }
  
  if (config.ggmlHip) script += '  -DGGML_HIP=ON \\\n'
  if (config.ggmlVulkan) script += '  -DGGML_VULKAN=ON \\\n'
  if (config.ggmlMetal) script += '  -DGGML_METAL=ON \\\n'
  if (config.ggmlOpencl) script += '  -DGGML_OPENCL=ON \\\n'
  if (config.ggmlBlast) {
    script += '  -DGGML_BLAS=ON \\\n'
    const blasVendors = ['Generic', 'ATLAS', 'BLIS', 'OpenBLAS', 'MKL', 'ONEAPI', 'BLIS']
    const blasVendor = blasVendors.includes(config.ggmlBlastVendor) ? config.ggmlBlastVendor : 'Generic'
    script += `  -DGGML_BLAS_VENDOR=${blasVendor} \\\n`
  }
  if (config.ggmlCann) script += '  -DGGML_CANN=ON \\\n'
  if (config.ggmlZendnn) script += '  -DGGML_ZENDNN=ON \\\n'
  if (config.ggmlKleidiai) script += '  -DGGML_CPU_KLEIDIAI=ON \\\n'
  
  script = script.replace(/ \\\n$/, '\n')
  script += 'cmake --build build --config ${CMAKE_BUILD_TYPE:-RelWithDebInfo} --parallel\n'
  
  return script
}

async function generateRunScript(config) {
  let script = '#!/bin/bash\n'
  script += '# Run Script for llama.cpp\n'
  script += `# Generated by Llama Manager\n\n`
  
  if (config.envVars) {
    script += 'export LLAMA_CACHE=${LLAMA_CACHE:-./cache}\n'
    for (const [key, value] of Object.entries(config.envVars)) {
      if (value) {
        script += `export ${key}=${value}\n`
      }
    }
    script += '\n'
  }
  
  script += './llama-server \\\n'
  
  if (config.modelPath) {
    script += `  -m "${config.modelPath}" \\\n`
  }
  
  if (config.contextSize) {
    script += `  -c ${config.contextSize} \\\n`
  }
  
  if (config.threads) {
    script += `  -t ${config.threads} \\\n`
  }
  
  if (config.threadsBatch) {
    script += `  -tb ${config.threadsBatch} \\\n`
  }
  
  if (config.batchSize) {
    script += `  -b ${config.batchSize} \\\n`
  }
  
  if (config.ubatchSize) {
    script += `  -ub ${config.ubatchSize} \\\n`
  }
  
  if (config.gpuLayers) {
    if (config.gpuLayers === 'all') {
      script += '  -ngl all \\\n'
    } else {
      script += `  -ngl ${config.gpuLayers} \\\n`
    }
  }
  
  if (config.mlock) script += '  --mlock \\\n'
  if (config.mmap) script += '  --mmap \\\n'
  if (config.directIo) script += '  --direct-io \\\n'
  
  if (config.numa) {
    const numaModes = ['off', 'bind', 'spread']
    const numaMode = numaModes.includes(config.numa) ? config.numa : 'off'
    script += `  --numa ${numaMode} \\\n`
  }
  
  if (config.contBatching) script += '  --cont-batching \\\n'
  if (config.kvUnified) script += '  --kv-unified \\\n'
  if (config.flashAttn) script += '  --flash-attn \\\n'
  
  if (config.cacheTypeK) {
    const cacheTypes = ['f16', 'q8_0', 'q4_0']
    const cacheTypeK = cacheTypes.includes(config.cacheTypeK) ? config.cacheTypeK : 'f16'
    script += `  --cache-type-k ${cacheTypeK} \\\n`
  }
  
  if (config.cacheTypeV) {
    const cacheTypes = ['f16', 'q8_0', 'q4_0']
    const cacheTypeV = cacheTypes.includes(config.cacheTypeV) ? config.cacheTypeV : 'f16'
    script += `  --cache-type-v ${cacheTypeV} \\\n`
  }
  
  if (config.splitMode) {
    const splitModes = ['none', 'layer', 'row']
    const splitMode = splitModes.includes(config.splitMode) ? config.splitMode : 'none'
    script += `  --split-mode ${splitMode} \\\n`
  }
  
  if (config.tensorSplit) {
    script += `  --tensor-split ${config.tensorSplit} \\\n`
  }
  
  if (config.mainGpu !== undefined && config.mainGpu !== null) {
    script += `  --main-gpu ${config.mainGpu} \\\n`
  }
  
  if (config.temperature) {
    script += `  --temp ${config.temperature} \\\n`
  }
  
  if (config.topK) {
    script += `  --top-k ${config.topK} \\\n`
  }
  
  if (config.topP) {
    script += `  --top-p ${config.topP} \\\n`
  }
  
  if (config.minP) {
    script += `  --min-p ${config.minP} \\\n`
  }
  
  if (config.typicalP) {
    script += `  --typical-p ${config.typicalP} \\\n`
  }
  
  if (config.repeatLastN) {
    script += `  --repeat-last-n ${config.repeatLastN} \\\n`
  }
  
  if (config.repeatPenalty) {
    script += `  --repeat-penalty ${config.repeatPenalty} \\\n`
  }
  
  if (config.presencePenalty) {
    script += `  --presence-penalty ${config.presencePenalty} \\\n`
  }
  
  if (config.frequencyPenalty) {
    script += `  --frequency-penalty ${config.frequencyPenalty} \\\n`
  }
  
  if (config.mirostat) {
    const mirostatModes = [0, 1, 2]
    const mirostatMode = mirostatModes.includes(config.mirostat) ? config.mirostat : 0
    script += `  --mirostat ${mirostatMode} \\\n`
  }
  
  if (config.grammar) {
    script += `  --grammar "${config.grammar}" \\\n`
  }
  
  if (config.jsonSchema) {
    script += `  --json-schema "${config.jsonSchema}" \\\n`
  }
  
  if (config.host) {
    script += `  --host ${config.host} \\\n`
  }
  
  if (config.port) {
    script += `  --port ${config.port} \\\n`
  }
  
  if (config.parallel) {
    script += `  --parallel ${config.parallel} \\\n`
  }
  
  if (config.webui) script += '  --webui \\\n'
  if (config.apiKey) {
    script += `  --api-key "${config.apiKey}" \\\n`
  }
  if (config.metrics) script += '  --metrics \\\n'
  if (config.timeout) {
    script += `  --timeout ${config.timeout} \\\n`
  }
  
  if (config.loraPath) {
    script += `  --lora "${config.loraPath}" \\\n`
  }
  
  if (config.mmprojPath) {
    script += `  --mmproj "${config.mmprojPath}" \\\n`
  }
  
  script = script.replace(/ \\\n$/, '\n')
  script += '\n'
  
  return script
}

app.get('/api/health', (req, res) => {
  res.json({ status: 'ok', timestamp: new Date().toISOString() })
})

app.get('/api/system-info', async (req, res) => {
  const os = await import('node:os')
  res.json({
    nodeVersion: process.version,
    platform: process.platform,
    arch: process.arch,
    cpus: os.cpus().length
  })
})

app.get('/api/configs/build', async (req, res) => {
  const configs = await readJsonFile('build-configs.json')
  res.json(configs)
})

app.post('/api/configs/build', async (req, res) => {
  const configs = await readJsonFile('build-configs.json')
  const newConfig = {
    id: req.body.id || `build-${Date.now()}`,
    name: req.body.name,
    config: req.body.config,
    createdAt: new Date().toISOString()
  }
  configs.push(newConfig)
  await writeJsonFile('build-configs.json', configs)
  res.json(newConfig)
})

app.put('/api/configs/build/:id', async (req, res) => {
  const configs = await readJsonFile('build-configs.json')
  const index = configs.findIndex(c => c.id === req.params.id)
  if (index === -1) {
    return res.status(404).json({ error: 'Configuration not found' })
  }
  configs[index] = {
    ...configs[index],
    config: req.body.config,
    name: req.body.name || configs[index].name,
    updatedAt: new Date().toISOString()
  }
  await writeJsonFile('build-configs.json', configs)
  res.json(configs[index])
})

app.delete('/api/configs/build/:id', async (req, res) => {
  const configs = await readJsonFile('build-configs.json')
  const filtered = configs.filter(c => c.id !== req.params.id)
  await writeJsonFile('build-configs.json', filtered)
  res.json({ success: true })
})

app.get('/api/configs/run', async (req, res) => {
  const configs = await readJsonFile('run-configs.json')
  res.json(configs)
})

app.post('/api/configs/run', async (req, res) => {
  const configs = await readJsonFile('run-configs.json')
  const newConfig = {
    id: req.body.id || `run-${Date.now()}`,
    name: req.body.name,
    config: req.body.config,
    createdAt: new Date().toISOString()
  }
  configs.push(newConfig)
  await writeJsonFile('run-configs.json', configs)
  res.json(newConfig)
})

app.put('/api/configs/run/:id', async (req, res) => {
  const configs = await readJsonFile('run-configs.json')
  const index = configs.findIndex(c => c.id === req.params.id)
  if (index === -1) {
    return res.status(404).json({ error: 'Configuration not found' })
  }
  configs[index] = {
    ...configs[index],
    config: req.body.config,
    name: req.body.name || configs[index].name,
    updatedAt: new Date().toISOString()
  }
  await writeJsonFile('run-configs.json', configs)
  res.json(configs[index])
})

app.delete('/api/configs/run/:id', async (req, res) => {
  const configs = await readJsonFile('run-configs.json')
  const filtered = configs.filter(c => c.id !== req.params.id)
  await writeJsonFile('run-configs.json', filtered)
  res.json({ success: true })
})

app.post('/api/scripts/build', async (req, res) => {
  try {
    const script = await generateBuildScript(req.body.config || req.body)
    res.json({ script })
  } catch (error) {
    res.status(500).json({ error: error.message })
  }
})

app.post('/api/scripts/run', async (req, res) => {
  try {
    const script = await generateRunScript(req.body.config || req.body)
    res.json({ script })
  } catch (error) {
    res.status(500).json({ error: error.message })
  }
})

app.get('/api/scripts/list', async (req, res) => {
  const scripts = []
  
  try {
    const buildScripts = await fs.readdir(join(SCRIPTS_DIR, 'builds'))
    for (const file of buildScripts) {
      if (file.endsWith('.sh')) {
        scripts.push({
          id: file.replace('.sh', ''),
          name: file.replace('.sh', ''),
          type: 'build',
          path: join(SCRIPTS_DIR, 'builds', file)
        })
      }
    }
  } catch (error) {}
  
  try {
    const runScripts = await fs.readdir(join(SCRIPTS_DIR, 'runs'))
    for (const file of runScripts) {
      if (file.endsWith('.sh')) {
        scripts.push({
          id: file.replace('.sh', ''),
          name: file.replace('.sh', ''),
          type: 'run',
          path: join(SCRIPTS_DIR, 'runs', file)
        })
      }
    }
  } catch (error) {}
  
  res.json(scripts)
})

app.get('/api/scripts/:id', async (req, res) => {
  const scriptPath = join(SCRIPTS_DIR, req.query.type === 'build' ? 'builds' : 'runs', `${req.params.id}.sh`)
  try {
    const content = await fs.readFile(scriptPath, 'utf-8')
    res.json({ id: req.params.id, content })
  } catch (error) {
    res.status(404).json({ error: 'Script not found' })
  }
})

app.post('/api/scripts/execute', async (req, res) => {
  const { scriptPath, args = [] } = req.body
  if (!scriptPath) {
    return res.status(400).json({ error: 'Script path required' })
  }
  
  try {
    await fs.access(scriptPath)
  } catch (error) {
    return res.status(404).json({ error: 'Script not found' })
  }
  
  const scriptDir = scriptPath.substring(0, scriptPath.lastIndexOf('/'))
  const scriptName = scriptPath.substring(scriptPath.lastIndexOf('/') + 1)
  
  exec(`chmod +x "${scriptPath}" && cd "${scriptDir}" && ./${scriptName} ${args.join(' ')}`, {
    maxBuffer: 10 * 1024 * 1024
  }, (error, stdout, stderr) => {
    if (error) {
      res.json({ 
        success: false, 
        error: error.message,
        stderr: stderr || ''
      })
      return
    }
    res.json({ 
      success: true, 
      output: stdout,
      stderr: stderr || ''
    })
  })
})

app.post('/api/scripts/save', async (req, res) => {
  const { name, type, content } = req.body
  if (!name || !type || !content) {
    return res.status(400).json({ error: 'name, type, and content required' })
  }
  
  const dir = join(SCRIPTS_DIR, type === 'build' ? 'builds' : 'runs')
  const filename = `${name.replace(/[^a-zA-Z0-9_-]/g, '-')}.sh`
  const filepath = join(dir, filename)
  
  await fs.mkdir(dir, { recursive: true })
  await fs.writeFile(filepath, content)
  
  res.json({ id: name.replace(/[^a-zA-Z0-9_-]/g, '-'), path: filepath })
})

app.delete('/api/scripts/:id', async (req, res) => {
  const { id } = req.params
  const type = req.query.type || 'run'
  
  const filepath = join(SCRIPTS_DIR, type === 'build' ? 'builds' : 'runs', `${id}.sh`)
  
  try {
    await fs.unlink(filepath)
    res.json({ success: true })
  } catch (error) {
    res.status(404).json({ error: 'Script not found' })
  }
})

app.get('/api/presets', async (req, res) => {
  try {
    const data = await fs.readFile(join(CONFIGS_DIR, 'presets.json'), 'utf-8')
    res.json(JSON.parse(data))
  } catch (error) {
    res.json({ build: [], run: [] })
  }
})

app.post('/api/hardware/detect', async (req, res) => {
  const { exec } = await import('child_process')
  
  exec('chmod +x /home/jon/git/llm_server/app/scripts/generate-recommendations.sh', (err) => {
    if (err) console.log('chmod warning:', err.message)
  })
  
  exec('/home/jon/git/llm_server/app/scripts/generate-recommendations.sh', {
    maxBuffer: 10 * 1024 * 1024
  }, (error, stdout, stderr) => {
    if (error) {
      return res.status(500).json({ 
        error: error.message,
        output: stdout || stderr
      })
    }
    
    try {
      const jsonMatch = stdout.match(/\{[\s\S]*\}/)
      if (jsonMatch) {
        const recommendations = JSON.parse(jsonMatch[0])
        res.json({
          success: true,
          recommendations,
          fullOutput: stdout
        })
      } else {
        res.status(500).json({ 
          error: 'Failed to parse recommendations',
          output: stdout
        })
      }
    } catch (parseError) {
      res.status(500).json({ 
        error: 'Failed to parse JSON',
        output: stdout,
        parseError: parseError.message
      })
    }
  })
})

app.use((req, res) => {
  res.sendFile(join(__dirname, 'dist', 'index.html'))
})

app.listen(PORT, () => {
  console.log(`Server running on port ${PORT}`)
})
